#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

target_name=$1

. vtkPath.config

rm -r bin

cmake   -S. -Bbuild \
        -DTARGET_DIR:PATH="$target_name" \
        -DVTK_DIR:PATH="$VTK_DIR" \
        -G "MinGW Makefiles"

cmake --build build --config Release
cmake --install build --config Release


cp "$VTK_BIN"/*-9.0.dll bin

cd bin
./main.exe
cd ..