#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

rm -r bin

binDir=bin
buildDir=build

cmake   -S. -B$buildDir \
        -DQt5_DIR:PATH="D:/Qt/5.12.4/mingw73_64/lib/cmake/Qt5" \
        -DQt5_BIN_DIR:PATH="/d/Qt/5.12.4/mingw73_64/bin" \
        -DCMAKE_BUILD_TYPE=Release \
        -G "MinGW Makefiles"

cmake --build $buildDir

cmake --install $buildDir
