#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

VTK_BIN_PATH_TO_COPY=/d/VTK-Release/bin

mkdir -p build/Release
rm -r bin

cd build/Release

cmake -DVTK_DIR:PATH=D:/VTK-Release/lib/cmake/vtk-8.2 ../.. -G "Visual Studio 16 2019"
cmake --build . --config Release
cmake --install . --config Release

cd ../..

# copy vtk dll
cp "$VTK_BIN_PATH_TO_COPY"/*8.2.dll bin/Release
